/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CursosIndexRouteImport } from './routes/cursos/index'
import { Route as CursosSlugRouteImport } from './routes/cursos/$slug'
import { Route as CursosAlongamentoDeCiliosRouteImport } from './routes/cursos/alongamento-de-cilios'
import { Route as CursosCabeleireiraProfissionalRouteImport } from './routes/cursos/cabeleireira-profissional'
import { Route as ApiGoogleAuthRouteImport } from './routes/api/google/auth'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiPublicAvailabilityRouteImport } from './routes/api/public/availability'
import { Route as ApiPublicBookingRouteImport } from './routes/api/public/booking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosAlongamentoDeCiliosRoute =
  CursosAlongamentoDeCiliosRouteImport.update({
    id: '/cursos/alongamento-de-cilios',
    path: '/cursos/alongamento-de-cilios',
    getParentRoute: () => rootRouteImport,
  } as any)
const CursosCabeleireiraProfissionalRoute =
  CursosCabeleireiraProfissionalRouteImport.update({
    id: '/cursos/cabeleireira-profissional',
    path: '/cursos/cabeleireira-profissional',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleAuthRoute = ApiGoogleAuthRouteImport.update({
  id: '/api/google/auth',
  path: '/api/google/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvailabilityRoute = ApiPublicAvailabilityRouteImport.update({
  id: '/api/public/availability',
  path: '/api/public/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingRoute = ApiPublicBookingRouteImport.update({
  id: '/api/public/booking',
  path: '/api/public/booking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/alongamento-de-cilios': typeof CursosAlongamentoDeCiliosRoute
  '/cursos/cabeleireira-profissional': typeof CursosCabeleireiraProfissionalRoute
  '/cursos/': typeof CursosIndexRoute
  '/api/google/auth': typeof ApiGoogleAuthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/public/availability': typeof ApiPublicAvailabilityRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/alongamento-de-cilios': typeof CursosAlongamentoDeCiliosRoute
  '/cursos/cabeleireira-profissional': typeof CursosCabeleireiraProfissionalRoute
  '/cursos': typeof CursosIndexRoute
  '/api/google/auth': typeof ApiGoogleAuthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/public/availability': typeof ApiPublicAvailabilityRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/alongamento-de-cilios': typeof CursosAlongamentoDeCiliosRoute
  '/cursos/cabeleireira-profissional': typeof CursosCabeleireiraProfissionalRoute
  '/cursos/': typeof CursosIndexRoute
  '/api/google/auth': typeof ApiGoogleAuthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/public/availability': typeof ApiPublicAvailabilityRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/chat'
    | '/cursos/$slug'
    | '/cursos/alongamento-de-cilios'
    | '/cursos/cabeleireira-profissional'
    | '/cursos/'
    | '/api/google/auth'
    | '/api/google/callback'
    | '/api/public/availability'
    | '/api/public/booking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/chat'
    | '/cursos/$slug'
    | '/cursos/alongamento-de-cilios'
    | '/cursos/cabeleireira-profissional'
    | '/cursos'
    | '/api/google/auth'
    | '/api/google/callback'
    | '/api/public/availability'
    | '/api/public/booking'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/chat'
    | '/cursos/$slug'
    | '/cursos/alongamento-de-cilios'
    | '/cursos/cabeleireira-profissional'
    | '/cursos/'
    | '/api/google/auth'
    | '/api/google/callback'
    | '/api/public/availability'
    | '/api/public/booking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  CursosSlugRoute: typeof CursosSlugRoute
  CursosAlongamentoDeCiliosRoute: typeof CursosAlongamentoDeCiliosRoute
  CursosCabeleireiraProfissionalRoute: typeof CursosCabeleireiraProfissionalRoute
  CursosIndexRoute: typeof CursosIndexRoute
  ApiGoogleAuthRoute: typeof ApiGoogleAuthRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiPublicAvailabilityRoute: typeof ApiPublicAvailabilityRoute
  ApiPublicBookingRoute: typeof ApiPublicBookingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/alongamento-de-cilios': {
      id: '/cursos/alongamento-de-cilios'
      path: '/cursos/alongamento-de-cilios'
      fullPath: '/cursos/alongamento-de-cilios'
      preLoaderRoute: typeof CursosAlongamentoDeCiliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/cabeleireira-profissional': {
      id: '/cursos/cabeleireira-profissional'
      path: '/cursos/cabeleireira-profissional'
      fullPath: '/cursos/cabeleireira-profissional'
      preLoaderRoute: typeof CursosCabeleireiraProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/auth': {
      id: '/api/google/auth'
      path: '/api/google/auth'
      fullPath: '/api/google/auth'
      preLoaderRoute: typeof ApiGoogleAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/availability': {
      id: '/api/public/availability'
      path: '/api/public/availability'
      fullPath: '/api/public/availability'
      preLoaderRoute: typeof ApiPublicAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking': {
      id: '/api/public/booking'
      path: '/api/public/booking'
      fullPath: '/api/public/booking'
      preLoaderRoute: typeof ApiPublicBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  CursosSlugRoute: CursosSlugRoute,
  CursosAlongamentoDeCiliosRoute: CursosAlongamentoDeCiliosRoute,
  CursosCabeleireiraProfissionalRoute: CursosCabeleireiraProfissionalRoute,
  CursosIndexRoute: CursosIndexRoute,
  ApiGoogleAuthRoute: ApiGoogleAuthRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiPublicAvailabilityRoute: ApiPublicAvailabilityRoute,
  ApiPublicBookingRoute: ApiPublicBookingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
